### ISSUE TITLE
Why are `<img>` elements given `display: table;`?

### ISSUE THREAD

**Issue by 6twenty** [cutestrap/cutestrap#29]
On one hand I'm just curious what the design choice here was about; on the other hand there's an issue when there's an `<img>` element within a container with `.ta-center` -- the image won't respect the text alignment. This can be worked around however by setting appropriate margins on the image:

```css
.ta-center img {
  margin-left: auto;
  margin-right: auto;
}

.ta-right img {
  margin-left: auto;
}
```
